spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/proposta
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true