spring:
  datasource:
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5434/proposta}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8080}

feign:
  client:
    situacao-financeira:
      url: ${URL_FINANCEIRO:http://localhost:9999/api/solicitacao}
    associa-cartao:
      url: ${URL_CARTOES:http://localhost:8888/api/cartoes}

associar:
  proposta:
    cartao:
      time:
        schedule: "25000"