spring:
  datasource:
    url: ${URL_DATABASE:jdbc:postgresql://localhost:5434/proposta}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}


management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
    prometheus:
      enabled: true
  metrics:
    tags:
      aplicacao: ${NOME_DA_APLICACAO:serviço de proposta}
      ambiente: ${AMBIENTE:desenvolvimento}

server:
  port: ${SERVER_PORT:8080}

feign:
  client:
    situacao-financeira:
      url: ${URL_FINANCEIRO:http://localhost:9999/api/solicitacao}
    cartoes:
      url: ${URL_CARTOES:http://localhost:8888/api/cartoes}

associar:
  proposta:
    cartao:
      time:
        schedule: "25000"